### ISSUE TITLE
Instance section. Searching

### ISSUE THREAD

**Issue by AndreiSulyz** [Skyro-ph/zeebe-simple-monitor#10]
Need to add a field to search for an instance by id, as well as filter data by start_date, end_time and state. 

You can use the form from the incidents section

**Comment by StaZisS** [comment]
Added this functionality in this [branch](https://github.com/Skyro-ph/zeebe-simple-monitor/tree/searching).

**Comment by StaZisS** [comment]
Also found a potential error in RequestParam(duplication param) in the [file](https://github.com/Skyro-ph/zeebe-simple-monitor/blob/searching/src/main/java/io/zeebe/monitor/rest/IncidentsViewController.java).
```java
  @GetMapping("/views/incidents")
  @Transactional
  public String incidentList(final Map<String, Object> model,
                             final Pageable pageable,
                             @RequestParam(required = false,name = "bpmnProcessId") String bpmnProcessId,
                             @RequestParam(required = false, name = "errorType") String errorType,
                             @RequestParam(required = false, name = "createdAfter") String createdAfter,
                             @RequestParam(required = false, name = "createdAfter") String createdBefore) {

```
